import { createBrowserRouter } from "react-router";
import { LaunchExperience } from "./components/LaunchExperience";
import { RoleSelection } from "./components/RoleSelection";
import { SignUp } from "./components/SignUp";
import { TellUsAboutYou } from "./components/TellUsAboutYou";
import { UploadVideo } from "./components/UploadVideo";
import { BuildProfile } from "./components/BuildProfile";
import { Experience } from "./components/Experience";
import { PersonalityTestIntro } from "./components/PersonalityTestIntro";
import { TestQuestions } from "./components/TestQuestions";
import { TestComplete } from "./components/TestComplete";
import { DiscoveryFeed } from "./components/DiscoveryFeed";
import { ExpandedProfile } from "./components/ExpandedProfile";
import { MatchScreen } from "./components/MatchScreen";
import { MessagesScreen } from "./components/MessagesScreen";
import { MyProfile } from "./components/MyProfile";
import { EventsList } from "./components/EventsList";
import { EventDetail } from "./components/EventDetail";
import { EventCreate } from "./components/EventCreate";
import { FounderDnaResults } from "./components/FounderDnaResults";
import { EntrepreneurProfile } from "./components/entrepreneur/EntrepreneurProfile";
import { EntrepreneurMotivation } from "./components/entrepreneur/EntrepreneurMotivation";
import { EntrepreneurEngagement } from "./components/entrepreneur/EntrepreneurEngagement";
import { EntrepreneurWorkingStyle } from "./components/entrepreneur/EntrepreneurWorkingStyle";
import { EntrepreneurPreferences } from "./components/entrepreneur/EntrepreneurPreferences";
import { EntrepreneurProject } from "./components/entrepreneur/EntrepreneurProject";

export const router = createBrowserRouter([
  { path: "/", Component: LaunchExperience },
  { path: "/choose-role", Component: RoleSelection },
  { path: "/signup", Component: SignUp },
  { path: "/about-you", Component: TellUsAboutYou },
  { path: "/upload-video", Component: UploadVideo },
  { path: "/profile", Component: BuildProfile },
  { path: "/experience", Component: Experience },
  { path: "/personality-test", Component: PersonalityTestIntro },
  { path: "/test/:questionId", Component: TestQuestions },
  { path: "/test-complete", Component: TestComplete },
  { path: "/discover", Component: DiscoveryFeed },
  { path: "/profile/:profileId", Component: ExpandedProfile },
  { path: "/match/:profileId", Component: MatchScreen },
  { path: "/messages", Component: MessagesScreen },
  { path: "/my-profile", Component: MyProfile },
  { path: "/events", Component: EventsList },
  { path: "/events/create", Component: EventCreate },
  { path: "/events/:id", Component: EventDetail },
  { path: "/founder-dna", Component: FounderDnaResults },
  // Entrepreneur onboarding
  { path: "/onboarding/entrepreneur/profile", Component: EntrepreneurProfile },
  { path: "/onboarding/entrepreneur/motivation", Component: EntrepreneurMotivation },
  { path: "/onboarding/entrepreneur/engagement", Component: EntrepreneurEngagement },
  { path: "/onboarding/entrepreneur/workingstyle", Component: EntrepreneurWorkingStyle },
  { path: "/onboarding/entrepreneur/preferences", Component: EntrepreneurPreferences },
  { path: "/onboarding/entrepreneur/project", Component: EntrepreneurProject },
]);
